# basic options
title: AIMS UK
author: Email us
email: aims.uk.charity@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  We are a UK-based charity supporting the projects of AIMS-PK in Pakistan - registered
  with the UK Charity Commission (# 1100864).
facebook_username: diabeteshospitalpeshawar


# Build settings
markdown: kramdown
theme: minima
