# basic options
title: AIMS UK
author: Email us
email: aims.uk.charity@gmail.com
show_excerpts: false # set to true to show excerpts on the homepage
description: > # this means to ignore newlines until "show_exerpts:"
  UK-based charity - Charity Commission #1100864
facebook_username: diabeteshospitalpeshawar


# Build settings
markdown: kramdown
theme: minima
